// voicepack.js - where the recorded cast lives, and how it gets to the game.
// GENERATED by the pack builder: do not edit the file list by hand.
//
// The cast is ElevenLabs takes (eleven_v4), trimmed, levelled and re-encoded
// as mono MP3. Brick has two casts and the player picks one (BRICK VOICE in
// the options): "John Texas", and "SteveM", a preview until the rest of his
// lines are recorded (a line he has not said yet is a subtitle), both at 40
// kbps. MUTTER is "Daniel" and the staff on the saw are "Dexter Glitch" (32
// kbps); Ilsa, who is on a radio, is "German Petra" (24 kbps at 16 kHz).
//
// There is far too much of it to put in the game file, so it ships beside it
// as plain scripts, voices/*.js, each adding its share of clips to
// globalThis.NUKEHAUS_VOICES as it loads. The game does not wait for them: it
// starts at once and the cast arrives behind it, the lines heard most first,
// and a line whose take is not here yet is a subtitle until it is.
//
// A clip is { r: role, k: line key, i: variant, a: the city it names (or null),
// t: the words, d: seconds, b: base64 mp3 } (acted.js plays them).

export const VOICE_FILES = [
  {"src": "voices/cast-0.js", "set": "cast", "tier": 0, "clips": 147, "bytes": 5588392},
  {"src": "voices/cast-1.js", "set": "cast", "tier": 0, "clips": 89, "bytes": 3991610},
  {"src": "voices/cast-2.js", "set": "cast", "tier": 1, "clips": 57, "bytes": 1973424},
  {"src": "voices/cast-3.js", "set": "cast", "tier": 2, "clips": 131, "bytes": 5544912},
  {"src": "voices/cast-4.js", "set": "cast", "tier": 2, "clips": 52, "bytes": 2214003},
  {"src": "voices/brick-stevem-0.js", "set": "stevem", "tier": 0, "clips": 159, "bytes": 5462575},
  {"src": "voices/brick-stevem-1.js", "set": "stevem", "tier": 1, "clips": 46, "bytes": 2007819},
  {"src": "voices/brick-texas-0.js", "set": "texas", "tier": 0, "clips": 164, "bytes": 5599488},
  {"src": "voices/brick-texas-1.js", "set": "texas", "tier": 0, "clips": 47, "bytes": 2003988},
  {"src": "voices/brick-texas-2.js", "set": "texas", "tier": 2, "clips": 126, "bytes": 5584528},
  {"src": "voices/brick-texas-3.js", "set": "texas", "tier": 2, "clips": 16, "bytes": 415143}
];

/**
 * Brick's casts, in the order the option steps through them. The first is the
 * default. A preview is a cast still being recorded: playable, not complete.
 */
export const BRICK_VOICES = [
  { id: 'texas', name: 'TEXAS' },
  { id: 'stevem', name: 'STEVEM', preview: true },
];

export function brickVoiceOk(id) { return BRICK_VOICES.some((v) => v.id === id); }

/** The files to fetch for a choice of Brick, the lines heard most first (Brick's before the rest's). */
export function voiceFilesFor(brick, sets = null) {
  const want = brickVoiceOk(brick) ? brick : BRICK_VOICES[0].id;
  return VOICE_FILES
    .filter((f) => (sets ? sets.includes(f.set) : f.set === 'cast' || f.set === want))
    .map((f, n) => ({ f, n }))
    .sort((a, b) => (a.f.tier - b.f.tier) || ((a.f.set === 'cast') - (b.f.set === 'cast')) || (a.n - b.n))
    .map((x) => x.f);
}

function drain(onClips) {
  const q = globalThis.NUKEHAUS_VOICES;
  let n = 0;
  while (Array.isArray(q) && q.length) {
    const p = q.shift();
    if (p && Array.isArray(p.clips) && p.clips.length) {
      n += p.clips.length;
      try { onClips(p.clips, p.set || 'cast'); } catch { /* the rest still arrive */ }
    }
  }
  return n;
}

/**
 * Fetch voice files, one at a time, in order: by default the whole cast with
 * Brick as `opts.brick`; `opts.sets` narrows it to some sets (switching Brick
 * fetches only his). `opts.want(file)`, asked just before each file is
 * fetched, can turn it down: a Brick the player has switched away from since
 * the list was made is not worth the download. `onClips(clips, set)` is
 * called as each file arrives. Resolves with how many clips came. A file that
 * cannot be had (the game opened from disk without its voices folder, say)
 * is skipped, and `opts.failed(file)` told, so it can be asked for again
 * later: the lines in it stay subtitles until then. `opts.base` goes in front
 * of each file's path.
 */
export function loadVoices(onClips, opts = {}) {
  const base = typeof opts.base === 'string' ? opts.base : '';
  const want = typeof opts.want === 'function' ? opts.want : () => true;
  const failed = typeof opts.failed === 'function' ? opts.failed : () => {};
  let n = drain(onClips);
  if (typeof document === 'undefined' || !document.createElement) return Promise.resolve(n);
  const one = (f) => new Promise((resolve) => {
    if (!want(f)) { resolve(); return; }
    try {
      const s = document.createElement('script');
      s.src = base + f.src;
      s.async = true;
      s.onload = () => { n += drain(onClips); resolve(); };
      s.onerror = () => { failed(f); resolve(); };
      (document.head || document.documentElement).appendChild(s);
    } catch { failed(f); resolve(); }
  });
  return voiceFilesFor(opts.brick, opts.sets).reduce((p, f) => p.then(() => one(f)), Promise.resolve()).then(() => n);
}

export default VOICE_FILES;
